language: python
python:
  - "2.7"
  - "3.3"

sudo: false

services:
  - redis-server

before_install:
  - pip install -U coveralls

install:
  - make install

script:
  - python setup.py pytest --addopts --cov=tapp_config

after_success:
  - coveralls
